/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "calculadora2.h"

bool_t
xdr_entrada (XDR *xdrs, entrada *objp)
{
	register int32_t *buf;

	 if (!xdr_pointer (xdrs, (char **)&objp->vector, sizeof (int), (xdrproc_t) xdr_int))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->longitud))
		 return FALSE;
	return TRUE;
}
