/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calculadora2.h"

int *
media_1_svc(entrada *argp, struct svc_req *rqstp)
{
	static int  result=0;
	int i;
	
	for(i=0; i< argp->longitud; i++)
		result = result + argp->vector[i];
	result = result/argp->longitud;

	return &result;
}

int *
maximo_1_svc(entrada *argp, struct svc_req *rqstp)
{
	static int  result;
	int i, aux;
	
	for(i=0; i< argp->longitud; i++){
		if(i==0){
			result = argp->vector[i];
			aux = result;
			}
		else if(aux>argp->vector[i])
			result = aux;
		else{;
			result = argp->vector[i];
			aux = result;
		}
	}
	
	return &result;
}

int *
factorial_1_svc(entrada *argp, struct svc_req *rqstp)
{
	static int result=1;
	int i;
	
	for(i=argp->vector[0]; i>0; i--)
		result=result * i;

	return &result;
}
